name: Environment Variables

on:
  push:
    branches:
      - main

jobs:
  learn-env:
    runs-on: ubuntu-latest

    env:
      APP_NAME: MyFirstApp
      NODE_ENV: production
      API_URL: https://api.test.com

    steps:
      - name: Print App Name
        run: echo $APP_NAME

      - name: Print Environment
        run: echo $NODE_ENV

      - name: Print API URL
        run: echo $API_URL
      - name: Print All Environment Variables
        run: env
