name: Environment Variables

on:
  push:
    branches:
      - main

jobs:
  learn-env:
    runs-on: ubuntu-latest

    env:
      APP_NAME: MyFirstApp
      NODE_ENV: production

    steps:
      - name: Print App Name
        run: echo $APP_NAME

      - name: Print Environment
        run: echo $NODE_ENV
